// <auto-generated />
using System;
using CfcShop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CfcShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810023246_UpdateProductImagePaths")]
    partial class UpdateProductImagePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CfcShop.Api.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home & Away Kits",
                            Description = "Official Chelsea FC Match Kits and Jerseys"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Training Wear",
                            Description = "Tracksuits, Jackets, and Training Apparel"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Accessories & Headwear",
                            Description = "Scarves, Caps, Bags, and Gloves"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Souvenirs & Collectibles",
                            Description = "Mugs, Keychains, Flags, and Memorabilia"
                        });
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 10, 2, 32, 43, 885, DateTimeKind.Utc).AddTicks(4407),
                            Description = "Official Chelsea FC 2024/25 Home Jersey featuring breathable Dri-FIT technology.",
                            ImageUrl = "/images/products/home-kit.jpg",
                            Price = 89.99m,
                            ProductCode = "KIT-CFC-001",
                            ProductName = "Chelsea FC 2024/25 Home Jersey",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 10, 2, 32, 43, 885, DateTimeKind.Utc).AddTicks(4419),
                            Description = "Official Chelsea FC 2024/25 Away Jersey with modern design and premium fabric.",
                            ImageUrl = "/images/products/away-kit.jpg",
                            Price = 89.99m,
                            ProductCode = "KIT-CFC-002",
                            ProductName = "Chelsea FC Away Jersey 2024/25",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 10, 2, 32, 43, 885, DateTimeKind.Utc).AddTicks(4421),
                            Description = "Comfortable Chelsea FC Anthem Track Jacket for training and casual wear.",
                            ImageUrl = "/images/products/anthem-jacket.jpg",
                            Price = 75.00m,
                            ProductCode = "TRN-CFC-001",
                            ProductName = "Chelsea FC Anthem Track Jacket",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 8, 10, 2, 32, 43, 885, DateTimeKind.Utc).AddTicks(4423),
                            Description = "Classic blue and white knitted Chelsea FC fan scarf.",
                            ImageUrl = "/images/products/chelsea-scarf.jpg",
                            Price = 25.00m,
                            ProductCode = "ACC-CFC-001",
                            ProductName = "Official Chelsea Scarf - Blue & White",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 8, 10, 2, 32, 43, 885, DateTimeKind.Utc).AddTicks(4426),
                            Description = "High quality ceramic mug with official Chelsea FC crest.",
                            ImageUrl = "/images/products/crest-mug.jpg",
                            Price = 15.00m,
                            ProductCode = "SOU-CFC-001",
                            ProductName = "Chelsea FC Crest Ceramic Mug",
                            StockQuantity = 75
                        });
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cfcshop.com",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$WoKM53LIv/p6FnImj2OA4eK.csocfbVu2ZWWFb2yIvqEYd2oX4h6S",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@cfcshop.com",
                            FullName = "Demo User",
                            PasswordHash = "$2a$11$e2ypceZPF2Kd9XwaLCvfXu89EQMbgqRX0XM4A72BAWQwnClExhxYi",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.CartItem", b =>
                {
                    b.HasOne("CfcShop.Api.Models.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CfcShop.Api.Models.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Order", b =>
                {
                    b.HasOne("CfcShop.Api.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("CfcShop.Api.Models.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CfcShop.Api.Models.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Product", b =>
                {
                    b.HasOne("CfcShop.Api.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.User", b =>
                {
                    b.HasOne("CfcShop.Api.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CfcShop.Api.Models.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
